paths:
  annot_root: "/kaggle/input/volleyball/volleyball_tracking_annotation/volleyball_tracking_annotation"
  videos_root: "/kaggle/input/volleyball/volleyball_/videos"

system:
  seed : 42
  
splits:
  train_ids: ['1','3','6','7','10','13','15','16','18','22','23','31','32','36','38','39','40','41','42','48','50','52','53','54']
  val_ids: ['0','2','8','12','17','19','24','26','27','28','30','33','46','49','51']
  test_ids: ['4','5','9','11','14','20','21','25','29','34','35','37','43','44','45','47']

model:
  arch: "Resnet50"  
  num_group_actions: 8

training:
  num_workers : 4
  pin_memory : True
  n_epoch: 20
  lr: 0.0001 # 1e-4
  batch_size: 16
  optimizer: "AdamW"
  criterion: "CrossEntropyLoss"

scheduler:
  type: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.1
  patience: 3
