paths:
  annot_root: "data/volleyball_tracking_annotation"
  videos_root: "data/videos_g10"

splits:
  train_ids: ['1','3','6','7','10','13','15','16','18','22','23','31','32','36','38','39','40','41','42','48','50','52','53','54']
  val_ids: ['0','2','8','12','17','19','24','26','27','28','30','33','46','49','51']
  test_ids: ['4','5','9','11','14','20','21','25','29','34','35','37','43','44','45','47']

model:
  arch: "b3_player_classifier + classifier for group "  
  num_player_actions: 9
  num_group_actions: 8

training:
  num_workers : 0
  pin_memory : False
  n_epoch: 3
  lr: 0.0001 # 1e-4
  batch_size: 1
  optimizer: "AdamW"
  criterion: "CrossEntropyLoss"

scheduler:
  type: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.1
  patience: 3
